apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-demo
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: blue-green-demo
  template:
    metadata:
      labels:
        app: blue-green-demo
    spec:
      containers:
      - name: blue-green-demo
        image: nginx:1.19.0
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: blue-green-demo-active
      previewService: blue-green-demo-preview
      autoPromotionEnabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-demo-active
  namespace: default
spec:
  selector:
    app: blue-green-demo
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-demo-preview
  namespace: default
spec:
  selector:
    app: blue-green-demo
  ports:
  - port: 80
    targetPort: 80
